### ISSUE TITLE
Kodi 18

### ISSUE THREAD

**Issue by datamaskinen** [alexbjorling/kodi-svt-oppetarkiv#6]
Hi there ... i don't know is this one is suppose to work with kodi 18 yet but this is the errors i get

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "/home/xxx/.kodi/addons/plugin.video.svt-oppetarkiv/addon.py", line 8, in <module>
                                                import resources.lib.svtoa as svtoa
                                              File "/home/xxx/.kodi/addons/plugin.video.svt-oppetarkiv/resources/lib/svtoa.py", line 8, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--

ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.svt-oppetarkiv/) failed

**Comment by alexbjorling** [comment]
Ah, that's an unmet dependency. You need the `requests` python package. On linux you can do  `pip install requests --user`, on win/mac probably something similar.

**Comment by datamaskinen** [comment]
aha ok thanks
